Big Update! I rewrite the workflow and remove the unused files.

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,11 +1,16 @@
-name: Build and Release YTMusicUltimate
-
+name: Build YTMusicUltimate IPA
 on:
   workflow_dispatch:
     inputs: 
       ipa_url:
         description: "URL to the decrypted IPA file"
         default: ""
+        required: true
+        type: string
+
+      ytmusicult_version:
+        description: "YTMusicUltimate Version (You can enter the version manually from YTMusicUltimate releases or leave default.)"
+        default: "2.3.1"
         required: true
         type: string
 
@@ -33,24 +38,33 @@ jobs:
       contents: write
 
     steps:
-      - name: Checkout Main
-        uses: actions/checkout@v4.1.1
-        with:
-          path: main
-          submodules: recursive
+      - name: Check Inputs
+        if: ${{ !inputs.upload_artifact && !inputs.draft_release && !inputs.catbox_upload }}
+        run: |
+          echo "No IPA output way selected. Please choose at least one."
+          exit 1
 
       - name: Hide sensitive inputs
         uses: levibostian/action-hide-sensitive-inputs@v1
+         with:
+          exclude_inputs: bundle_id,display_name,ytmusicult_version,draft_release,upload_artifact,catbox_upload
 
-      - name: Validate IPA URL
+      - name: Download and Validate IPA
         run: |
-          curl -L -r 0-1023 -o sample.part "${{ inputs.ipa_url }}" > /dev/null 2>&1
-          file_type=$(file --mime-type -b sample.part)
+          wget "${{ inputs.ipa_url }}" --no-verbose -O ${{ github.workspace }}/ytm.ipa
+
+          file_type=$(file --mime-type -b ${{ github.workspace }}/ytm.ipa)
 
           if [[ "$file_type" != "application/x-ios-app" && "$file_type" != "application/zip" ]]; then
-            echo "::error::Validation failed: The file is not a valid IPA file. Detected type: $file_type."
+            echo "::error::Validation failed: The downloaded file is not a valid IPA. Detected type: $file_type."
             exit 1
           fi
+
+      - name: Get YouTube Music Version 
+        run: |
+          unzip -q ${{ github.workspace }}/ytm.ipa -d ${{ github.workspace }}/ytmextracted
+          echo "YTM_VERSION=$(grep -A 1 '<key>CFBundleVersion</key>' ${{ github.workspace }}/ytmextracted/Payload/YouTubeMusic.app/Info.plist | grep '<string>' | awk -F'[><]' '{print $3}')" >> $GITHUB_ENV
+          echo -e 'Done!'
 
       - name: Install Dependencies
         run: brew install make ldid
@@ -58,31 +72,14 @@ jobs:
       - name: Set PATH environment variable
         run: echo "$(brew --prefix make)/libexec/gnubin" >> $GITHUB_PATH
 
-      - name: Cache Theos
-        id: theos
-        uses: actions/cache@v4.2.3
-        env:
-          cache-name: theos_cache_67db2ab
-        with:
-          path: theos/
-          key: ${{ env.cache-name }}
-          restore-keys: ${{ env.cache-name }}
-
-      - name: Setup Theos
-        if: steps.theos.outputs.cache-hit != 'true'
-        uses: actions/checkout@v4.1.7
-        with:
-          repository: theos/theos
-          ref: 67db2ab8d950910161730de77c322658ea3e6b44
-          path: ${{ github.workspace }}/theos
-          submodules: recursive
+      - name: Clone Theos
+         run: git clone --quiet --recurse-submodules https://github.com/theos/theos.git
 
       - name: Download iOS SDK
-        if: steps.theos.outputs.cache-hit != 'true'
         run: |
-          git clone --quiet -n --depth=1 --filter=tree:0 https://github.com/theos/sdks/
-          cd sdks
-          git sparse-checkout set --no-cone iPhoneOS16.5.sdk
+          git clone --quiet -n --depth=1 --filter=tree:0 https://github.com/xybp888/iOS-SDKs.git
+          cd iOS-SDKs
+          git sparse-checkout set --no-cone iPhoneOS18.6.sdk
           git checkout
           mv *.sdk $THEOS/sdks
         env:
@@ -91,34 +88,89 @@ jobs:
       - name: Install cyan
         run: pipx install --force https://github.com/asdfzxcvbn/pyzule-rw/archive/main.zip
 
-      - name: Download YouTube Music
-        id: download_youtube_music
-        run: wget "${{ inputs.ipa_url }}" --no-verbose -O ${{ github.workspace }}/main/ytm.ipa
+      - name: Download YTMusicUltimate .deb
+        run: wget "https://github.com/dayanch96/YTMusicUltimate/releases/download/v${{ inputs.ytmusicult_version }}/com.ginsu.ytmusicultimate_${{ inputs.ytmusicult_version }}_iphoneos-arm64.deb" --no-verbose -O ${{ github.workspace }}/ytmusicult.deb
 
-      - name: Build Tweak for Sideloading
-        id: build_package
+      - name: Clone NoYTMPremium
+        run: git clone --quiet https://github.com/PoomSmart/NoYTMPremium.git
+
+      - name: Clone YTMABConfig
+        run: git clone --quiet https://github.com/PoomSmart/YTMABConfig.git
+
+      - name: Build NoYTMPremium
         run: |
-          cd ${{ github.workspace }}/main
-          make clean package SIDELOADING=1 WERROR=0 \
-            ADDITIONAL_OBJCXXFLAGS="-Wno-vla-cxx-extension -Wno-error=vla-cxx-extension" \
-            ADDITIONAL_CFLAGS="-Wno-vla -Wno-error=vla"
+          cd ${{ github.workspace }}/NoYTMPremium
+          make clean package DEBUG=0 FINALPACKAGE=1
+          mv packages/*.deb ${{ github.workspace }}/notympremium.deb
+        env:
+          THEOS: ${{ github.workspace }}/theos    
+
+      - name: Build YTMABConfig
+        run: |
+          cd ${{ github.workspace }}/YTMABConfig
+          make clean package DEBUG=0 FINALPACKAGE=1
+          mv packages/*.deb ${{ github.workspace }}/ytmab.deb
         env:
           THEOS: ${{ github.workspace }}/theos
 
-      - name: Inject tweak into provided IPA
-        run: |
-          cd ${{ github.workspace }}/main/packages
-          tweakName=$(ls)
-          cd ${{ github.workspace }}/main
-          cyan -i ytm.ipa -o packages/YTMusicUltimate.ipa -uwsf packages/$tweakName -n "${{ inputs.display_name }}" -b ${{ inputs.bundle_id }} 
 
-      - name: Create Release
-        uses: softprops/action-gh-release@v2.0.6
+      - name: Inject Tweaks Into IPA
+        run: |
+          tweaks="ytmusicult.deb"
+
+          for f in *.deb; do
+            if [ -f "$f" ]; then
+              tweaks="$tweaks $f"
+            fi
+          done
+
+          cyan -i ytm.ipa -o YTMusicUltimate_${{ env.YTM_VERSION }}_v${{ inputs.ytmusicult_version }}.ipa -uwef $tweaks -n "${{ inputs.display_name }}" -b ${{ inputs.bundle_id }} 
+
+      - name: Upload IPA to Catbox
+        if: ${{ inputs.catbox_upload }}
+        run: |
+          RESPONSE=$(curl -F "reqtype=fileupload" -F "fileToUpload=@${{ github.workspace }}/YTMusicUltimate_${{ env.YTM_VERSION }}_v${{ inputs.ytmusicult_version }}.ipa" https://catbox.moe/user/api.php)
+          CATBOX_URL=$(echo $RESPONSE | grep -o -E 'https://files.catbox.moe/[^"]*')
+          echo "Uploaded artifact to $CATBOX_URL"
+          CATBOX_FILE=$(echo $CATBOX_URL | sed 's|https://files.catbox.moe/||')
+          echo "CATBOX_FILE=$CATBOX_FILE" >> $GITHUB_ENV
+          echo "CATBOX_URL=$CATBOX_URL" >> $GITHUB_ENV
+
+      - name: Upload IPA as an Artifact
+        if: ${{ inputs.upload_artifact }}
+        uses: actions/upload-artifact@v4.6.2
         with:
-          name: YTMusicUltimate-v${{ github.run_number }}
-          files: main/packages/*.ipa
+          name: YTMusicUltimate_${{ env.YTM_VERSION }}_v${{ inputs.ytmusicult_version }}
+          path: ${{ github.workspace }}/YTMusicUltimate_${{ env.YTM_VERSION }}_v${{ inputs.ytmusicult_version }}.ipa
+
+      - name: Create a Draft Release
+        if: ${{ inputs.draft_release }}
+        uses: softprops/action-gh-release@v2.3.3
+        with:
+          tag_name: ytmult-ipa${{ github.run_number }}
+          name: YTMusicUltimate_${{ env.YTM_VERSION }}_v${{ inputs.ytmusicult_version }} (${{ github.run_number }}) 
+          files: YTMusicUltimate_${{ env.YTM_VERSION }}_v${{ inputs.ytmusicult_version }}.ipa
           draft: true
 
-      - name: Output Release URL
+      - name: Job Summary - Build Conplete
         run: |
-          echo "::notice::Release available at: https://github.com/${{ github.repository }}/releases"
+          echo -e '### 🛠️ Build YTMusicUltimate IPA Complete!' >> $GITHUB_STEP_SUMMARY
+
+      - name: Job Summary - Output the Artifact Upload
+        if: ${{ inputs.upload_artifact }}
+        run: |
+          echo -e '### 📦 Artifact Upload\n\nUpload IPA as an artifact successfully! [Scroll down](#artifacts) to view the artifact. Note that you must be signed in to GitHub to download it.' >> $GITHUB_STEP_SUMMARY
+
+      - name: Job Summary - Output the IPA URL (Catbox Upload)
+        if: ${{ inputs.catbox_upload }}
+        run: |
+          echo -e '### 🐱 Catbox Upload\n\nUpload IPA to Catbox successfully! Here is a permanent shareable link: '$CATBOX_URL >> $GITHUB_STEP_SUMMARY
+
+      - name: Job Summary - Output a Draft Release Link
+        if: ${{ inputs.draft_release }}
+        run: |
+          echo -e '### 🚀 Draft Release\n\nDraft release has been created successfully! You can view your release here: https://github.com/${{ github.repository }}/releases' >> $GITHUB_STEP_SUMMARY
+     
+      - name: Job Summary - Cleanup
+        run: |
+          echo -e '### 🧹 Cleanup\n\nYou can remove previous GitHub Actions run here: https://github.com/${{ github.repository }}/actions/workflows/delete-old-workflow-runs.yml' >> $GITHUB_STEP_SUMMARY
